//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiadas.Domain.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Olimpiadas.Domain.Entities.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para desactivar el último atractivo activo, primero desactive la ruta a la cual pertenece.
        /// </summary>
        public static string Atractivo_DesactivacionDenegada {
            get {
                return ResourceManager.GetString("Atractivo_DesactivacionDenegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El atractivo no se puede activar, primero debe cargar todas sus imagenes.
        /// </summary>
        public static string Atractivo_FaltaImagenes {
            get {
                return ResourceManager.GetString("Atractivo_FaltaImagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario o la contraseña son incorrectos.
        /// </summary>
        public static string AutenticacionUsuario_DatosIncorrectos {
            get {
                return ResourceManager.GetString("AutenticacionUsuario_DatosIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario &quot;{0}&quot;, se encuentra inactivo.
        /// </summary>
        public static string AutenticacionUsuario_NoActivo {
            get {
                return ResourceManager.GetString("AutenticacionUsuario_NoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario &quot;{0}&quot;, no se encuentra registrado en el sistema.
        /// </summary>
        public static string AutenticacionUsuario_NoRegistrado {
            get {
                return ResourceManager.GetString("AutenticacionUsuario_NoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de avatares activos no puede superar los 10..
        /// </summary>
        public static string Avatar_DemasiadosNiveles {
            get {
                return ResourceManager.GetString("Avatar_DemasiadosNiveles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe registrado un avatar para el nivel ingresado, desactive el avatar de nombre: &quot;{0}&quot;.
        /// </summary>
        public static string Avatar_NivelExistente {
            get {
                return ResourceManager.GetString("Avatar_NivelExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El puntaje mínimo debe ser mayor al puntaje mínimo del avatar del nivel anterior.
        /// </summary>
        public static string Avatar_PuntajeMinimoNoValido {
            get {
                return ResourceManager.GetString("Avatar_PuntajeMinimoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El puntaje mínimo debe ser menor al puntaje mínimo del avatar del nivel posterior..
        /// </summary>
        public static string Avatar_PuntajeMinimoNoValidoPosterior {
            get {
                return ResourceManager.GetString("Avatar_PuntajeMinimoNoValidoPosterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe asignar valores a los siguientes campos: {0}.
        /// </summary>
        public static string GeneralAsignacionValores {
            get {
                return ResourceManager.GetString("GeneralAsignacionValores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código: &quot;{0}&quot; ya se encuentra registrado y esta asiganado a: &quot;{1}&quot;.
        /// </summary>
        public static string GeneralCodigoRegistrado {
            get {
                return ResourceManager.GetString("GeneralCodigoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad {0} tiene el valor incorecto.
        /// </summary>
        public static string GenereralCadenaValorIncorrecto {
            get {
                return ResourceManager.GetString("GenereralCadenaValorIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad {0} debe tener {1} caracteres.
        /// </summary>
        public static string GenereralTamanioFijoIncorrecto {
            get {
                return ResourceManager.GetString("GenereralTamanioFijoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Iconografía ya existe.
        /// </summary>
        public static string Iconografia_Existente {
            get {
                return ResourceManager.GetString("Iconografia_Existente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se envió correctamente.
        /// </summary>
        public static string MensajeEnviadoCorrectamente {
            get {
                return ResourceManager.GetString("MensajeEnviadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se envió a su correo un código de 4 cifras para su validación.
        /// </summary>
        public static string Notificacion_CorreoEnviadoExitosamente {
            get {
                return ResourceManager.GetString("Notificacion_CorreoEnviadoExitosamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha enviado satisfactoriamente la contraseña a su correo.
        /// </summary>
        public static string Notificacion_EnviadoExitosamenteRecuperarContrasenia {
            get {
                return ResourceManager.GetString("Notificacion_EnviadoExitosamenteRecuperarContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La notificación automática no existe.
        /// </summary>
        public static string NotificacionValidacion_NoExiste {
            get {
                return ResourceManager.GetString("NotificacionValidacion_NoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proceso se ha interrumpido debido a errores, por favor revisar..
        /// </summary>
        public static string Oferta_ProcesoFallido {
            get {
                return ResourceManager.GetString("Oferta_ProcesoFallido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La pregunta no se puede activar, debe tener por lo menos 2 respuestas activas..
        /// </summary>
        public static string Pregunta_DebeTener2RespuestasActivas {
            get {
                return ResourceManager.GetString("Pregunta_DebeTener2RespuestasActivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La pregunta no se puede activar, debe tener por lo menos 1 respuesta activa..
        /// </summary>
        public static string Pregunta_DebeTenerRespuestasActivas {
            get {
                return ResourceManager.GetString("Pregunta_DebeTenerRespuestasActivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe registrada una pregunta para la numeración ingresada, por favor vuelva a ingresar.
        /// </summary>
        public static string Pregunta_NumeracionExistente {
            get {
                return ResourceManager.GetString("Pregunta_NumeracionExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha y hora programada inválidas, debe ser por lo menos 2 minutos mayor a la fecha actual.
        /// </summary>
        public static string Push_ValidacionFechaHora {
            get {
                return ResourceManager.GetString("Push_ValidacionFechaHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La respuesta no se puede desactivar, debido a que la pregunta es de opción multiple, y es obligatorio tener como mínimo 2 respuestas activas..
        /// </summary>
        public static string Respuesta_DebeTener2RespuestasActivas {
            get {
                return ResourceManager.GetString("Respuesta_DebeTener2RespuestasActivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La respuesta no se puede desactivar, debido a que la pregunta es de opción única y es obligatorio tener como mínimo 1 respuesta activa..
        /// </summary>
        public static string Respuesta_DebeTenerRespuestasActivas {
            get {
                return ResourceManager.GetString("Respuesta_DebeTenerRespuestasActivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe registrada una respuesta para la numeración ingresada, por favor vuelva a ingresar.
        /// </summary>
        public static string Respuesta_NumeracionExistente {
            get {
                return ResourceManager.GetString("Respuesta_NumeracionExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ruta no se puede activar, debe tener por lo menos un atractivo activo.
        /// </summary>
        public static string Ruta_FaltaAtractivosActivos {
            get {
                return ResourceManager.GetString("Ruta_FaltaAtractivosActivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ruta no se puede activar, primero debe cargar todas sus imagenes.
        /// </summary>
        public static string Ruta_FaltaImagenes {
            get {
                return ResourceManager.GetString("Ruta_FaltaImagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha del código ingresado ha expirado, por favor vuelva a solicitar código.
        /// </summary>
        public static string TokenValidacion_CodigoFechaExpirada {
            get {
                return ResourceManager.GetString("TokenValidacion_CodigoFechaExpirada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código que ha enviado no coincide con su correo electrónico, por favor intente nuevamente.
        /// </summary>
        public static string TokenValidacion_CodigoIncorrecto {
            get {
                return ResourceManager.GetString("TokenValidacion_CodigoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario aún no ha validado su código de 4 cifras..
        /// </summary>
        public static string TokenValidacion_CodigoNoValidado {
            get {
                return ResourceManager.GetString("TokenValidacion_CodigoNoValidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código ya fue usado el {0}.
        /// </summary>
        public static string TokenValidacion_CodigoUsado {
            get {
                return ResourceManager.GetString("TokenValidacion_CodigoUsado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ese correo ya se encuentra registrado en la página de YTQP ¿Desea usar ese mismo correo para este aplicativo?.
        /// </summary>
        public static string Turista_DeseaUsarCorreoYTQP {
            get {
                return ResourceManager.GetString("Turista_DeseaUsarCorreoYTQP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar el mensaje, por favor revise si su correo electrónico es correcto.
        /// </summary>
        public static string Turista_MensajeNoEnviado {
            get {
                return ResourceManager.GetString("Turista_MensajeNoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar la notificación Push, por favor verifique su configuración.
        /// </summary>
        public static string Turista_PushNoEnviado {
            get {
                return ResourceManager.GetString("Turista_PushNoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su contraseña ha sido actualizada correctamente.
        /// </summary>
        public static string TuristaNotificacion_ContraseniaActualizadaCorrectamente {
            get {
                return ResourceManager.GetString("TuristaNotificacion_ContraseniaActualizadaCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña nueva no debe ser igual a la contraseña actual.
        /// </summary>
        public static string TuristaValidacion_ContraseniaActualIgualNueva {
            get {
                return ResourceManager.GetString("TuristaValidacion_ContraseniaActualIgualNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña actual ingresada no es correcta, por favor reintentar.
        /// </summary>
        public static string TuristaValidacion_ContraseniaActualIncorrecta {
            get {
                return ResourceManager.GetString("TuristaValidacion_ContraseniaActualIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener mínimo 6 caracteres, por favor ingresar de nuevo.
        /// </summary>
        public static string TuristaValidacion_ContraseniaMinimoCaracteres {
            get {
                return ResourceManager.GetString("TuristaValidacion_ContraseniaMinimoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas ingresadas no coinciden, por favor ingresar de nuevo.
        /// </summary>
        public static string TuristaValidacion_ContraseniasNoCoinciden {
            get {
                return ResourceManager.GetString("TuristaValidacion_ContraseniasNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos incorrectos en sistema YTQP.
        /// </summary>
        public static string TuristaValidacion_DatosIncorrectosEnYTQP {
            get {
                return ResourceManager.GetString("TuristaValidacion_DatosIncorrectosEnYTQP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para poder registrarse en el app debe ser mayor de edad.
        /// </summary>
        public static string TuristaValidacion_EdadInvalida {
            get {
                return ResourceManager.GetString("TuristaValidacion_EdadInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hemos detectado que su email ya existe en la web de YTQP ¿Desea usar la misma cuenta para este aplicativo?.
        /// </summary>
        public static string TuristaValidacion_ExisteUsuarioEnYTQP {
            get {
                return ResourceManager.GetString("TuristaValidacion_ExisteUsuarioEnYTQP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe aceptar el contrato de Privacidad del aplicativo.
        /// </summary>
        public static string TuristaValidacion_PrivacidadEsObligatorio {
            get {
                return ResourceManager.GetString("TuristaValidacion_PrivacidadEsObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe aceptar los Términos y Condiciones del aplicativo.
        /// </summary>
        public static string TuristaValidacion_TerminosEsObligatorio {
            get {
                return ResourceManager.GetString("TuristaValidacion_TerminosEsObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha cambiado el correo electrónico que ingresó, por favor reintentar.
        /// </summary>
        public static string TuristaValidacion_TokenTemporalIncorrecto {
            get {
                return ResourceManager.GetString("TuristaValidacion_TokenTemporalIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico no registrado.
        /// </summary>
        public static string TuristaValidacion_UsuarioNoExiste {
            get {
                return ResourceManager.GetString("TuristaValidacion_UsuarioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario {0} esta bloqueado, consulte con el Adminsitrador del Sistema o espere hasta el día de mañana..
        /// </summary>
        public static string Usuario_Bloqueado {
            get {
                return ResourceManager.GetString("Usuario_Bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña ingresada es incorrecta.
        /// </summary>
        public static string Usuario_ContraseniaActualIncorrecta {
            get {
                return ResourceManager.GetString("Usuario_ContraseniaActualIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las credenciales son inválidas.
        /// </summary>
        public static string Usuario_CredencialesInvalidas {
            get {
                return ResourceManager.GetString("Usuario_CredencialesInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario {0} se encuentra desactivado..
        /// </summary>
        public static string Usuario_Desactivado {
            get {
                return ResourceManager.GetString("Usuario_Desactivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El email &quot;{0}&quot; ya se encuentra registrado a nombre de {1}..
        /// </summary>
        public static string Usuario_EmailExistente {
            get {
                return ResourceManager.GetString("Usuario_EmailExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe especificar el correo electrónico.
        /// </summary>
        public static string Usuario_EmailNoIngresado {
            get {
                return ResourceManager.GetString("Usuario_EmailNoIngresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se encuentra inactivo.
        /// </summary>
        public static string Usuario_Inactivo {
            get {
                return ResourceManager.GetString("Usuario_Inactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario aún no ha sido registrado.
        /// </summary>
        public static string Usuario_LoginNoExiste {
            get {
                return ResourceManager.GetString("Usuario_LoginNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario {0} no tiene los permisos necesarios.
        /// </summary>
        public static string Usuario_SinRoles {
            get {
                return ResourceManager.GetString("Usuario_SinRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La recuperacion de contraseña no es valido para autenticacion por dominio.
        /// </summary>
        public static string Usuario_ValidarRecuperarContraseniaDominio {
            get {
                return ResourceManager.GetString("Usuario_ValidarRecuperarContraseniaDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su contraseña ha sido actualizada correctamente.
        /// </summary>
        public static string UsuarioNotificacion_ContraseniaActualizadaCorrectamente {
            get {
                return ResourceManager.GetString("UsuarioNotificacion_ContraseniaActualizadaCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña nueva no debe ser igual a la contraseña actual.
        /// </summary>
        public static string UsuarioValidacion_ContraseniaActualIgualNueva {
            get {
                return ResourceManager.GetString("UsuarioValidacion_ContraseniaActualIgualNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña actual ingresada no es correcta, por favor reintentar.
        /// </summary>
        public static string UsuarioValidacion_ContraseniaActualIncorrecta {
            get {
                return ResourceManager.GetString("UsuarioValidacion_ContraseniaActualIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener mínimo 6 caracteres, por favor ingresar de nuevo.
        /// </summary>
        public static string UsuarioValidacion_ContraseniaMinimoCaracteres {
            get {
                return ResourceManager.GetString("UsuarioValidacion_ContraseniaMinimoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas ingresadas no coinciden, por favor ingresar de nuevo.
        /// </summary>
        public static string UsuarioValidacion_ContraseniasNoCoinciden {
            get {
                return ResourceManager.GetString("UsuarioValidacion_ContraseniasNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El dominio ingresado es incorrecto.
        /// </summary>
        public static string UsuarioValidacion_DominioIncorrecto {
            get {
                return ResourceManager.GetString("UsuarioValidacion_DominioIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El email ingresado es incorrecto.
        /// </summary>
        public static string UsuarioValidacion_EmailIncorrecto {
            get {
                return ResourceManager.GetString("UsuarioValidacion_EmailIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario de dominio no existe.
        /// </summary>
        public static string UsuarioValidacion_LoginDominioIncorrecto {
            get {
                return ResourceManager.GetString("UsuarioValidacion_LoginDominioIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cambio de contraseña no es valido para autenticación por dominio.
        /// </summary>
        public static string UsuarioValidacion_TipoAutenticacionDominio {
            get {
                return ResourceManager.GetString("UsuarioValidacion_TipoAutenticacionDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no registrado en YTQP.
        /// </summary>
        public static string UsuarioValidacion_UsuarioNoExiste {
            get {
                return ResourceManager.GetString("UsuarioValidacion_UsuarioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no registrado en Rutas Cortas.
        /// </summary>
        public static string UsuarioValidacion_UsuarioNoExisteRutasCortas {
            get {
                return ResourceManager.GetString("UsuarioValidacion_UsuarioNoExisteRutasCortas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese la contraseña que uso para registrarse en la web de YTQP.
        /// </summary>
        public static string UsuarioYTQP_ContraseniaIncorrecta {
            get {
                return ResourceManager.GetString("UsuarioYTQP_ContraseniaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de días de aviso inválida.
        /// </summary>
        public static string ValidacionDiasFechaProgramada {
            get {
                return ResourceManager.GetString("ValidacionDiasFechaProgramada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresar la fecha.
        /// </summary>
        public static string ValidacionFechaNull {
            get {
                return ResourceManager.GetString("ValidacionFechaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha inicial debe ser mayor a la fecha final.
        /// </summary>
        public static string ValidacionFechasInicioFin {
            get {
                return ResourceManager.GetString("ValidacionFechasInicioFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los detalles para el grupo y destino seleccionado ya fueron registrados.
        /// </summary>
        public static string ValidadionIconografiasPendientes {
            get {
                return ResourceManager.GetString("ValidadionIconografiasPendientes", resourceCulture);
            }
        }
    }
}
