//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiadas.Domain.Entities.GestionContenido
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///
    /// </summary>
    public partial class ComplejoDeportivo
    {
    	/// <summary>
        /// Incializa una nueva instancia de la clase.
        /// </summary>
        public ComplejoDeportivo()
        {
            this.Localizacion = new HashSet<Localizacion>();
            this.MaterialMantenimiento = new HashSet<MaterialMantenimiento>();
        }
    
    
        /// <summary>
        ///
        /// </summary>
        public int IdComplejo { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public int IdSede { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public string NombreComplejo { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public int IdTipoComplejo { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public string Direccion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public int IdJefeComplejo { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public decimal TotalAreaOcupada { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public decimal Presupuesto { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public bool Activo { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public System.DateTime FechaCreacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdComplejo{ get {return "IdComplejo"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdSede{ get {return "IdSede"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_NombreComplejo{ get {return "NombreComplejo"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdTipoComplejo{ get {return "IdTipoComplejo"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_Direccion{ get {return "Direccion"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdJefeComplejo{ get {return "IdJefeComplejo"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_TotalAreaOcupada{ get {return "TotalAreaOcupada"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_Presupuesto{ get {return "Presupuesto"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_Activo{ get {return "Activo"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_FechaCreacion{ get {return "FechaCreacion"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_FechaModificacion{ get {return "FechaModificacion"; }}
    
    
    	/// <summary>
        /// Propiedad de navegación a Participante
        /// </summary>
        public virtual Participante Participante { get; set; }
    
    	/// <summary>
        /// Propiedad de navegación a Sede
        /// </summary>
        public virtual Sede Sede { get; set; }
    
    	/// <summary>
        /// Propiedad de navegación a Tipo
        /// </summary>
        public virtual Tipo Tipo { get; set; }
    
    	/// <summary>
        /// Propiedad de navegación a Localizacion
        /// </summary>
        public virtual ICollection<Localizacion> Localizacion { get; set; }
    
    	/// <summary>
        /// Propiedad de navegación a MaterialMantenimiento
        /// </summary>
        public virtual ICollection<MaterialMantenimiento> MaterialMantenimiento { get; set; }
    
    }
}
