//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiadas.Domain.Entities.GestionContenido
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///
    /// </summary>
    public partial class Evento
    {
    	/// <summary>
        /// Incializa una nueva instancia de la clase.
        /// </summary>
        public Evento()
        {
            this.Comisario = new HashSet<Comisario>();
            this.MaterialEvento = new HashSet<MaterialEvento>();
            this.Registro = new HashSet<Registro>();
        }
    
    
        /// <summary>
        ///
        /// </summary>
        public int IdEvento { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public int IdDeporte { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public int IdLocalizacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public System.DateTime FechaEvento { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public System.TimeSpan HoraInicioEvento { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public bool TieneDuracionEvento { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public Nullable<int> DuracionMinutosEvento { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public Nullable<System.TimeSpan> HoraFinEvento { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public int CantidadParticipantesEvento { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public int CantidadComisariosEvento { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public int IdEstadoEvento { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public bool Activo { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public System.DateTime FechaCreacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdEvento{ get {return "IdEvento"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdDeporte{ get {return "IdDeporte"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdLocalizacion{ get {return "IdLocalizacion"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_FechaEvento{ get {return "FechaEvento"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_HoraInicioEvento{ get {return "HoraInicioEvento"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_TieneDuracionEvento{ get {return "TieneDuracionEvento"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_DuracionMinutosEvento{ get {return "DuracionMinutosEvento"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_HoraFinEvento{ get {return "HoraFinEvento"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_CantidadParticipantesEvento{ get {return "CantidadParticipantesEvento"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_CantidadComisariosEvento{ get {return "CantidadComisariosEvento"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdEstadoEvento{ get {return "IdEstadoEvento"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_Activo{ get {return "Activo"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_FechaCreacion{ get {return "FechaCreacion"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_FechaModificacion{ get {return "FechaModificacion"; }}
    
    
    	/// <summary>
        /// Propiedad de navegación a Comisario
        /// </summary>
        public virtual ICollection<Comisario> Comisario { get; set; }
    
    	/// <summary>
        /// Propiedad de navegación a Localizacion
        /// </summary>
        public virtual Localizacion Localizacion { get; set; }
    
    	/// <summary>
        /// Propiedad de navegación a Tipo
        /// </summary>
        public virtual Tipo Tipo { get; set; }
    
    	/// <summary>
        /// Propiedad de navegación a Tipo1
        /// </summary>
        public virtual Tipo Tipo1 { get; set; }
    
    	/// <summary>
        /// Propiedad de navegación a MaterialEvento
        /// </summary>
        public virtual ICollection<MaterialEvento> MaterialEvento { get; set; }
    
    	/// <summary>
        /// Propiedad de navegación a Registro
        /// </summary>
        public virtual ICollection<Registro> Registro { get; set; }
    
    }
}
