//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiadas.Domain.Entities.GestionContenido
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///
    /// </summary>
    public partial class Grupo
    {
    	/// <summary>
        /// Incializa una nueva instancia de la clase.
        /// </summary>
        public Grupo()
        {
            this.Tipo = new HashSet<Tipo>();
        }
    
    
        /// <summary>
        ///
        /// </summary>
        public int IdGrupo { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public string NombreGrupo { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public bool Activo { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdGrupo{ get {return "IdGrupo"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_NombreGrupo{ get {return "NombreGrupo"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_Activo{ get {return "Activo"; }}
    
    
    	/// <summary>
        /// Propiedad de navegación a Tipo
        /// </summary>
        public virtual ICollection<Tipo> Tipo { get; set; }
    
    }
}
