//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiadas.Domain.Entities.GestionContenido
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///
    /// </summary>
    public partial class Localizacion
    {
    	/// <summary>
        /// Incializa una nueva instancia de la clase.
        /// </summary>
        public Localizacion()
        {
            this.Evento = new HashSet<Evento>();
        }
    
    
        /// <summary>
        ///
        /// </summary>
        public int IdLocalizacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public int IdComplejo { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public string NombreLocalizacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public bool Activo { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public System.DateTime FechaCreacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdLocalizacion{ get {return "IdLocalizacion"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdComplejo{ get {return "IdComplejo"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_NombreLocalizacion{ get {return "NombreLocalizacion"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_Activo{ get {return "Activo"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_FechaCreacion{ get {return "FechaCreacion"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_FechaModificacion{ get {return "FechaModificacion"; }}
    
    
    	/// <summary>
        /// Propiedad de navegación a ComplejoDeportivo
        /// </summary>
        public virtual ComplejoDeportivo ComplejoDeportivo { get; set; }
    
    	/// <summary>
        /// Propiedad de navegación a Evento
        /// </summary>
        public virtual ICollection<Evento> Evento { get; set; }
    
    }
}
