//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiadas.Domain.Entities.GestionContenido
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///
    /// </summary>
    public partial class Participante
    {
    	/// <summary>
        /// Incializa una nueva instancia de la clase.
        /// </summary>
        public Participante()
        {
            this.ComplejoDeportivo = new HashSet<ComplejoDeportivo>();
            this.Registro = new HashSet<Registro>();
        }
    
    
        /// <summary>
        ///
        /// </summary>
        public int IdParticipante { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public string NombreParticipante { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public int IdPais { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public int IdDeporte { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public bool Activo { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public System.DateTime FechaCreacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdParticipante{ get {return "IdParticipante"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_NombreParticipante{ get {return "NombreParticipante"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdPais{ get {return "IdPais"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdDeporte{ get {return "IdDeporte"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_Activo{ get {return "Activo"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_FechaCreacion{ get {return "FechaCreacion"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_FechaModificacion{ get {return "FechaModificacion"; }}
    
    
    	/// <summary>
        /// Propiedad de navegación a ComplejoDeportivo
        /// </summary>
        public virtual ICollection<ComplejoDeportivo> ComplejoDeportivo { get; set; }
    
    	/// <summary>
        /// Propiedad de navegación a Tipo
        /// </summary>
        public virtual Tipo Tipo { get; set; }
    
    	/// <summary>
        /// Propiedad de navegación a Tipo1
        /// </summary>
        public virtual Tipo Tipo1 { get; set; }
    
    	/// <summary>
        /// Propiedad de navegación a Registro
        /// </summary>
        public virtual ICollection<Registro> Registro { get; set; }
    
    }
}
