//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiadas.Domain.Entities.GestionContenido
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///
    /// </summary>
    public partial class Personal
    {
    	/// <summary>
        /// Incializa una nueva instancia de la clase.
        /// </summary>
        public Personal()
        {
            this.Comisario = new HashSet<Comisario>();
        }
    
    
        /// <summary>
        ///
        /// </summary>
        public int IdPersonal { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public string NombrePersonal { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public string DniPersonal { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public bool Activo { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public System.DateTime FechaCreacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdPersonal{ get {return "IdPersonal"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_NombrePersonal{ get {return "NombrePersonal"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_DniPersonal{ get {return "DniPersonal"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_Activo{ get {return "Activo"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_FechaCreacion{ get {return "FechaCreacion"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_FechaModificacion{ get {return "FechaModificacion"; }}
    
    
    	/// <summary>
        /// Propiedad de navegación a Comisario
        /// </summary>
        public virtual ICollection<Comisario> Comisario { get; set; }
    
    }
}
