//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiadas.Domain.Entities.GestionContenido
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///
    /// </summary>
    public partial class Sede
    {
    	/// <summary>
        /// Incializa una nueva instancia de la clase.
        /// </summary>
        public Sede()
        {
            this.ComplejoDeportivo = new HashSet<ComplejoDeportivo>();
        }
    
    
        /// <summary>
        ///
        /// </summary>
        public int IdSede { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public string NombreSede { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public int CantidadComplejosSede { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public decimal PresupuestoTotalSede { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public bool Activo { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public System.DateTime FechaCreacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdSede{ get {return "IdSede"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_NombreSede{ get {return "NombreSede"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_CantidadComplejosSede{ get {return "CantidadComplejosSede"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_PresupuestoTotalSede{ get {return "PresupuestoTotalSede"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_Activo{ get {return "Activo"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_FechaCreacion{ get {return "FechaCreacion"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_FechaModificacion{ get {return "FechaModificacion"; }}
    
    
    	/// <summary>
        /// Propiedad de navegación a ComplejoDeportivo
        /// </summary>
        public virtual ICollection<ComplejoDeportivo> ComplejoDeportivo { get; set; }
    
    }
}
