//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiadas.Domain.Entities.GestionSeguridad
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///
    /// </summary>
    public partial class Usuario
    {
    
        /// <summary>
        ///
        /// </summary>
        public int IdUsuario { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public string LoginUsuario { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public byte[] Contrasenia { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public string NombreUsuario { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public string ApellidoUsuario { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public string EmailUsuario { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public bool Activo { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public System.DateTime FechaCreacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_IdUsuario{ get {return "IdUsuario"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_LoginUsuario{ get {return "LoginUsuario"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_Contrasenia{ get {return "Contrasenia"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_NombreUsuario{ get {return "NombreUsuario"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_ApellidoUsuario{ get {return "ApellidoUsuario"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_EmailUsuario{ get {return "EmailUsuario"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_Activo{ get {return "Activo"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_FechaCreacion{ get {return "FechaCreacion"; }}
    
    
        /// <summary>
        ///
        /// </summary>
        public static string Propiedad_FechaModificacion{ get {return "FechaModificacion"; }}
    
    }
}
