//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiadas.Presentation.ServiceAgents.Proxy.GestionContenido {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="PROMPERU.GestionContenidoService", ConfigurationName="Proxy.GestionContenido.IGestionContenidoService", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IGestionContenidoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalPaginar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalPaginarResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(Olimpiadas.Application.Dto.Fault.ServiceErrorResponseDto), Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalPaginarServiceE" +
            "rrorResponseDtoFault", Name="ServiceErrorResponseDto", Namespace="http://schemas.datacontract.org/2004/07/Olimpiadas.Application.Dto.Fault")]
        Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalPaginacionResponseDto PersonalPaginar(Olimpiadas.Application.Dto.Comun.PaginacionRequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalPaginar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalPaginarResponse" +
            "")]
        System.Threading.Tasks.Task<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalPaginacionResponseDto> PersonalPaginarAsync(Olimpiadas.Application.Dto.Comun.PaginacionRequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalObtenerEditor", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalObtenerEditorRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Olimpiadas.Application.Dto.Fault.ServiceErrorResponseDto), Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalObtenerEditorSe" +
            "rviceErrorResponseDtoFault", Name="ServiceErrorResponseDto", Namespace="http://schemas.datacontract.org/2004/07/Olimpiadas.Application.Dto.Fault")]
        Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalEditorResponseDto PersonalObtenerEditor(System.Nullable<int> idPersonal);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalObtenerEditor", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalObtenerEditorRe" +
            "sponse")]
        System.Threading.Tasks.Task<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalEditorResponseDto> PersonalObtenerEditorAsync(System.Nullable<int> idPersonal);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalInsertar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalInsertarRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(Olimpiadas.Application.Dto.Fault.ServiceErrorResponseDto), Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalInsertarService" +
            "ErrorResponseDtoFault", Name="ServiceErrorResponseDto", Namespace="http://schemas.datacontract.org/2004/07/Olimpiadas.Application.Dto.Fault")]
        int PersonalInsertar(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalInsertar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalInsertarRespons" +
            "e")]
        System.Threading.Tasks.Task<int> PersonalInsertarAsync(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalActualizar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalActualizarRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Olimpiadas.Application.Dto.Fault.ServiceErrorResponseDto), Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalActualizarServi" +
            "ceErrorResponseDtoFault", Name="ServiceErrorResponseDto", Namespace="http://schemas.datacontract.org/2004/07/Olimpiadas.Application.Dto.Fault")]
        void PersonalActualizar(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalActualizar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalActualizarRespo" +
            "nse")]
        System.Threading.Tasks.Task PersonalActualizarAsync(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalDesactivar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalDesactivarRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Olimpiadas.Application.Dto.Fault.ServiceErrorResponseDto), Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalDesactivarServi" +
            "ceErrorResponseDtoFault", Name="ServiceErrorResponseDto", Namespace="http://schemas.datacontract.org/2004/07/Olimpiadas.Application.Dto.Fault")]
        void PersonalDesactivar(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalDesactivar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalDesactivarRespo" +
            "nse")]
        System.Threading.Tasks.Task PersonalDesactivarAsync(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalActivar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalActivarResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(Olimpiadas.Application.Dto.Fault.ServiceErrorResponseDto), Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalActivarServiceE" +
            "rrorResponseDtoFault", Name="ServiceErrorResponseDto", Namespace="http://schemas.datacontract.org/2004/07/Olimpiadas.Application.Dto.Fault")]
        void PersonalActivar(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalActivar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/PersonalActivarResponse" +
            "")]
        System.Threading.Tasks.Task PersonalActivarAsync(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipantePaginar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipantePaginarResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Olimpiadas.Application.Dto.Fault.ServiceErrorResponseDto), Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipantePaginarServ" +
            "iceErrorResponseDtoFault", Name="ServiceErrorResponseDto", Namespace="http://schemas.datacontract.org/2004/07/Olimpiadas.Application.Dto.Fault")]
        Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipantePaginacionResponseDto ParticipantePaginar(Olimpiadas.Application.Dto.Comun.PaginacionRequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipantePaginar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipantePaginarResp" +
            "onse")]
        System.Threading.Tasks.Task<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipantePaginacionResponseDto> ParticipantePaginarAsync(Olimpiadas.Application.Dto.Comun.PaginacionRequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteObtenerEdit" +
            "or", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteObtenerEdit" +
            "orResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Olimpiadas.Application.Dto.Fault.ServiceErrorResponseDto), Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteObtenerEdit" +
            "orServiceErrorResponseDtoFault", Name="ServiceErrorResponseDto", Namespace="http://schemas.datacontract.org/2004/07/Olimpiadas.Application.Dto.Fault")]
        Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteEditorResponseDto ParticipanteObtenerEditor(System.Nullable<int> idParticipante);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteObtenerEdit" +
            "or", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteObtenerEdit" +
            "orResponse")]
        System.Threading.Tasks.Task<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteEditorResponseDto> ParticipanteObtenerEditorAsync(System.Nullable<int> idParticipante);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteInsertar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteInsertarRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Olimpiadas.Application.Dto.Fault.ServiceErrorResponseDto), Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteInsertarSer" +
            "viceErrorResponseDtoFault", Name="ServiceErrorResponseDto", Namespace="http://schemas.datacontract.org/2004/07/Olimpiadas.Application.Dto.Fault")]
        int ParticipanteInsertar(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteInsertar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteInsertarRes" +
            "ponse")]
        System.Threading.Tasks.Task<int> ParticipanteInsertarAsync(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteActualizar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteActualizarR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Olimpiadas.Application.Dto.Fault.ServiceErrorResponseDto), Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteActualizarS" +
            "erviceErrorResponseDtoFault", Name="ServiceErrorResponseDto", Namespace="http://schemas.datacontract.org/2004/07/Olimpiadas.Application.Dto.Fault")]
        void ParticipanteActualizar(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteActualizar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteActualizarR" +
            "esponse")]
        System.Threading.Tasks.Task ParticipanteActualizarAsync(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteDesactivar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteDesactivarR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Olimpiadas.Application.Dto.Fault.ServiceErrorResponseDto), Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteDesactivarS" +
            "erviceErrorResponseDtoFault", Name="ServiceErrorResponseDto", Namespace="http://schemas.datacontract.org/2004/07/Olimpiadas.Application.Dto.Fault")]
        void ParticipanteDesactivar(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteDesactivar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteDesactivarR" +
            "esponse")]
        System.Threading.Tasks.Task ParticipanteDesactivarAsync(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteActivar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteActivarResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Olimpiadas.Application.Dto.Fault.ServiceErrorResponseDto), Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteActivarServ" +
            "iceErrorResponseDtoFault", Name="ServiceErrorResponseDto", Namespace="http://schemas.datacontract.org/2004/07/Olimpiadas.Application.Dto.Fault")]
        void ParticipanteActivar(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteActivar", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/ParticipanteActivarResp" +
            "onse")]
        System.Threading.Tasks.Task ParticipanteActivarAsync(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/Prueba", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/PruebaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Olimpiadas.Application.Dto.Fault.ServiceErrorResponseDto), Action="PROMPERU.GestionContenidoService/IGestionContenidoService/PruebaServiceErrorRespo" +
            "nseDtoFault", Name="ServiceErrorResponseDto", Namespace="http://schemas.datacontract.org/2004/07/Olimpiadas.Application.Dto.Fault")]
        string Prueba();
        
        [System.ServiceModel.OperationContractAttribute(Action="PROMPERU.GestionContenidoService/IGestionContenidoService/Prueba", ReplyAction="PROMPERU.GestionContenidoService/IGestionContenidoService/PruebaResponse")]
        System.Threading.Tasks.Task<string> PruebaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionContenidoServiceChannel : Olimpiadas.Presentation.ServiceAgents.Proxy.GestionContenido.IGestionContenidoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionContenidoServiceClient : System.ServiceModel.ClientBase<Olimpiadas.Presentation.ServiceAgents.Proxy.GestionContenido.IGestionContenidoService>, Olimpiadas.Presentation.ServiceAgents.Proxy.GestionContenido.IGestionContenidoService {
        
        public GestionContenidoServiceClient() {
        }
        
        public GestionContenidoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionContenidoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionContenidoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionContenidoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalPaginacionResponseDto PersonalPaginar(Olimpiadas.Application.Dto.Comun.PaginacionRequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request) {
            return base.Channel.PersonalPaginar(request);
        }
        
        public System.Threading.Tasks.Task<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalPaginacionResponseDto> PersonalPaginarAsync(Olimpiadas.Application.Dto.Comun.PaginacionRequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request) {
            return base.Channel.PersonalPaginarAsync(request);
        }
        
        public Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalEditorResponseDto PersonalObtenerEditor(System.Nullable<int> idPersonal) {
            return base.Channel.PersonalObtenerEditor(idPersonal);
        }
        
        public System.Threading.Tasks.Task<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalEditorResponseDto> PersonalObtenerEditorAsync(System.Nullable<int> idPersonal) {
            return base.Channel.PersonalObtenerEditorAsync(idPersonal);
        }
        
        public int PersonalInsertar(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request) {
            return base.Channel.PersonalInsertar(request);
        }
        
        public System.Threading.Tasks.Task<int> PersonalInsertarAsync(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request) {
            return base.Channel.PersonalInsertarAsync(request);
        }
        
        public void PersonalActualizar(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request) {
            base.Channel.PersonalActualizar(request);
        }
        
        public System.Threading.Tasks.Task PersonalActualizarAsync(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request) {
            return base.Channel.PersonalActualizarAsync(request);
        }
        
        public void PersonalDesactivar(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request) {
            base.Channel.PersonalDesactivar(request);
        }
        
        public System.Threading.Tasks.Task PersonalDesactivarAsync(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request) {
            return base.Channel.PersonalDesactivarAsync(request);
        }
        
        public void PersonalActivar(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request) {
            base.Channel.PersonalActivar(request);
        }
        
        public System.Threading.Tasks.Task PersonalActivarAsync(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Personal.PersonalDto> request) {
            return base.Channel.PersonalActivarAsync(request);
        }
        
        public Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipantePaginacionResponseDto ParticipantePaginar(Olimpiadas.Application.Dto.Comun.PaginacionRequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request) {
            return base.Channel.ParticipantePaginar(request);
        }
        
        public System.Threading.Tasks.Task<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipantePaginacionResponseDto> ParticipantePaginarAsync(Olimpiadas.Application.Dto.Comun.PaginacionRequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request) {
            return base.Channel.ParticipantePaginarAsync(request);
        }
        
        public Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteEditorResponseDto ParticipanteObtenerEditor(System.Nullable<int> idParticipante) {
            return base.Channel.ParticipanteObtenerEditor(idParticipante);
        }
        
        public System.Threading.Tasks.Task<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteEditorResponseDto> ParticipanteObtenerEditorAsync(System.Nullable<int> idParticipante) {
            return base.Channel.ParticipanteObtenerEditorAsync(idParticipante);
        }
        
        public int ParticipanteInsertar(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request) {
            return base.Channel.ParticipanteInsertar(request);
        }
        
        public System.Threading.Tasks.Task<int> ParticipanteInsertarAsync(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request) {
            return base.Channel.ParticipanteInsertarAsync(request);
        }
        
        public void ParticipanteActualizar(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request) {
            base.Channel.ParticipanteActualizar(request);
        }
        
        public System.Threading.Tasks.Task ParticipanteActualizarAsync(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request) {
            return base.Channel.ParticipanteActualizarAsync(request);
        }
        
        public void ParticipanteDesactivar(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request) {
            base.Channel.ParticipanteDesactivar(request);
        }
        
        public System.Threading.Tasks.Task ParticipanteDesactivarAsync(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request) {
            return base.Channel.ParticipanteDesactivarAsync(request);
        }
        
        public void ParticipanteActivar(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request) {
            base.Channel.ParticipanteActivar(request);
        }
        
        public System.Threading.Tasks.Task ParticipanteActivarAsync(Olimpiadas.Application.Dto.Comun.RequestDto<Olimpiadas.Application.Dto.GestionContenido.Participante.ParticipanteDto> request) {
            return base.Channel.ParticipanteActivarAsync(request);
        }
        
        public string Prueba() {
            return base.Channel.Prueba();
        }
        
        public System.Threading.Tasks.Task<string> PruebaAsync() {
            return base.Channel.PruebaAsync();
        }
    }
}
