//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiadas.CrossCutting.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesElementoHtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesElementoHtml() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Olimpiadas.CrossCutting.Strings.ResourcesElementoHtml", typeof(ResourcesElementoHtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td class=&quot;column-action column-activar&quot;&gt;&lt;a onclick=&quot;{0}({1});&quot; title=&quot;Activar&quot;&gt;Activar&lt;/a&gt;&lt;/td&gt;.
        /// </summary>
        public static string ColumnActivar_IdNumeric {
            get {
                return ResourceManager.GetString("ColumnActivar_IdNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td class=&quot;column-action column-activar&quot;&gt;&lt;a data1=&quot;{0}&quot; data2=&quot;{1}&quot; title=&quot;Activar&quot;&gt;Activar&lt;/a&gt;&lt;/td&gt;.
        /// </summary>
        public static string ColumnActivar_IdNumeric_2Params {
            get {
                return ResourceManager.GetString("ColumnActivar_IdNumeric_2Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td class=&quot;column-action column-activar&quot;&gt;&lt;a data1=&quot;{0}&quot; title=&quot;Activar&quot;&gt;Activar&lt;/a&gt;&lt;/td&gt;.
        /// </summary>
        public static string ColumnActivar_IdString {
            get {
                return ResourceManager.GetString("ColumnActivar_IdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td class=&quot;column-action column-del&quot;&gt;&lt;a onclick=&quot;{0}({1});&quot; title=&quot;Desactivar&quot;&gt;Desactivar&lt;/a&gt;&lt;/td&gt;.
        /// </summary>
        public static string ColumnDesactivar_IdNumeric {
            get {
                return ResourceManager.GetString("ColumnDesactivar_IdNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td class=&quot;column-action column-del&quot;&gt;&lt;a data1=&quot;{0}&quot; data2=&quot;{1}&quot; title=&quot;Desactivar&quot;&gt;Desactivar&lt;/a&gt;&lt;/td&gt;.
        /// </summary>
        public static string ColumnDesactivar_IdNumeric_2Params {
            get {
                return ResourceManager.GetString("ColumnDesactivar_IdNumeric_2Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td class=&quot;column-action column-del&quot;&gt;&lt;a data1=&quot;{0}&quot; title=&quot;Desactivar&quot;&gt;Desactivar&lt;/a&gt;&lt;/td&gt;.
        /// </summary>
        public static string ColumnDesactivar_IdString {
            get {
                return ResourceManager.GetString("ColumnDesactivar_IdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td class=&quot;column-action column-print&quot;&gt;&lt;a onclick=&quot;{0}({1});&quot; title=&quot;Imprimir&quot;&gt;Imprimir&lt;/a&gt;&lt;/td&gt;.
        /// </summary>
        public static string ColumnPrint_IdNumeric {
            get {
                return ResourceManager.GetString("ColumnPrint_IdNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td class=&quot;column-action column-set&quot;&gt;&lt;a data1=&quot;{0}&quot; title=&quot;Modificar&quot;&gt;Modificar&lt;/a&gt;&lt;/td&gt;.
        /// </summary>
        public static string ColumnSet_IdNumeric {
            get {
                return ResourceManager.GetString("ColumnSet_IdNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td class=&quot;column-action column-set&quot;&gt;&lt;a data1=&quot;{0}&quot; data2=&quot;{1}&quot; title=&quot;Modificar&quot;&gt;Modificar&lt;/a&gt;&lt;/td&gt;.
        /// </summary>
        public static string ColumnSet_IdNumeric_2Params {
            get {
                return ResourceManager.GetString("ColumnSet_IdNumeric_2Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td class=&quot;column-action column-set&quot;&gt;&lt;a onclick=&quot;{0}(&apos;{1}&apos;);&quot; title=&quot;Modificar&quot;&gt;Modificar&lt;/a&gt;&lt;/td&gt;.
        /// </summary>
        public static string ColumnSet_IdString {
            get {
                return ResourceManager.GetString("ColumnSet_IdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td class=&quot;column-action column-set&quot;&gt;&lt;a onclick=&quot;{0}(&apos;{1}&apos;,&apos;{2}&apos;);&quot; title=&quot;Modificar&quot;&gt;Modificar&lt;/a&gt;&lt;/td&gt;.
        /// </summary>
        public static string ColumnSet_IdString_2Params {
            get {
                return ResourceManager.GetString("ColumnSet_IdString_2Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id-layout-body.
        /// </summary>
        public static string LayoutBody {
            get {
                return ResourceManager.GetString("LayoutBody", resourceCulture);
            }
        }
    }
}
